services:
  db:
    image: bitnami/mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: SchoolOnDb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped

volumes:
  db_data: