services:
  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: SchoolOnDb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./server.js:/app/server.js
    restart: unless-stopped

  # frontend:
  #   build: ../frontend-techchallenge
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - app
  #   restart: unless-stopped

volumes:
  db_data: